# Top-level configuration
name = "gfriend"
main = "./.svelte-kit/tsconfig.json"
compatibility_date = "2025-03-07"

workers_dev = false
route = { pattern = "www.buddyville.xyz/*", zone_name = "www.buddyville.xyz" }